from prague.feature_vector import make_random_objects, load_object_vectors
from prague.feature_vector import upper_closure, lower_closure
from prague.feature_vector import objects_to_extension_vector, extension_vector_to_objects
from prague.feature_vector import extension, extensions
from prague.feature_vector import get_pfvs_whose_extension_contains
from prague.feature_vector import get_pfvs_whose_extension_is_exactly
from prague.feature_vector import meet_specification as meet
from prague.feature_vector import lte_specification as lte

import prague.convert
